Add a new "direct" biblio display style
tabatkins/bikeshed pull request #2191
Opened 2021-12-06 19:08 UTC by brycelelbach

Add a new biblio display style, "direct", which displays references by their shortname and links to the referenced document. Closes #2032.

2021-12-08 22:14 UTC, tabatkins commented on bikeshed/shorthands/oldShorthands.py
> +    if (displayInline + displayIndex + displayDirect) > 1:
I hate that Python bool is technically a subclass of int, but I suppose it has its uses...

2021-12-08 22:15 UTC, tabatkins commented on docs/index.bs
> +    displaying as their shortname and linking to the referenced document ("direct").
your indent is broken

2021-12-08 22:15 UTC, tabatkins commented on docs/index.bs
> +  You can make them display "direct", where they link straight to the document,
broken indent

2021-12-08 22:17 UTC, tabatkins requested changes
The feature looks good. Only problem is the busted indents in the docs, which'll break the formatting when I actually process them.

When you fix those, would you mind running Bikeshed over it and including the results in the PR, too?

2021-12-15 13:22 UTC, brycelelbach commented
D'oh. Looks like I missed the fact that the docs use tabs! I was wondering if I should regenerate them.

I've fixed the indents and added regenerated docs to the PR. I also rebased on `main` (and regenerated the tests and docs afterwards just to be safe).

2021-12-15 19:50 UTC, merged

2021-12-16 17:10 UTC, brycelelbach commented
Thanks!